# Generated by Django 5.0.3 on 2024-03-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_alter_client_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
            ],
        ),
    ]
